FROM alpine

# Python3 とそのシンボリックリンクをインストール
RUN apk add --update python3 py3-pip \
    && ln -sf python3 /usr/bin/python

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

USER trainee

CMD ["python", "-V"]
